# Generated by Django 3.0.8 on 2020-07-15 00:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.ImageField(max_length=20, upload_to='')),
                ('estado_civil', models.CharField(choices=[('s', 'Solteiro'), ('n', 'Namorando'), ('no', 'Noivando'), ('c', 'Casado'), ('v', 'Viuvo'), ('p', 'Piranhage')], max_length=2)),
                ('data_nascimento', models.DateField()),
                ('estado', models.CharField(choices=[('rs', 'Rio Grande do Sul'), ('sc', 'Santa Catarina'), ('pr', 'Paraná')], max_length=2)),
                ('cidade', models.CharField(max_length=64)),
                ('desempregado', models.BooleanField()),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
