# Generated by Django 3.0.8 on 2020-07-16 22:55

from django.db import migrations, models
import pessoa.models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0002_auto_20200714_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='seguindo',
            field=models.ManyToManyField(related_name='_perfil_seguindo_+', to='pessoa.Perfil'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='data_nascimento',
            field=models.DateField(validators=[pessoa.models.validador_idade]),
        ),
    ]
